# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arran/Projects/WAIVE/03_Plugin/DPFTutorial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arran/Projects/WAIVE/03_Plugin/DPFTutorial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arran/Projects/WAIVE/03_Plugin/DPFTutorial/CMakeFiles /home/arran/Projects/WAIVE/03_Plugin/DPFTutorial//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arran/Projects/WAIVE/03_Plugin/DPFTutorial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dgl-opengl

# Build rule for target.
dgl-opengl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dgl-opengl
.PHONY : dgl-opengl

# fast build rule for target.
dgl-opengl/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/dgl-opengl.dir/build.make plugins/AITest/CMakeFiles/dgl-opengl.dir/build
.PHONY : dgl-opengl/fast

#=============================================================================
# Target rules for targets named AITest

# Build rule for target.
AITest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest
.PHONY : AITest

# fast build rule for target.
AITest/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest.dir/build.make plugins/AITest/CMakeFiles/AITest.dir/build
.PHONY : AITest/fast

#=============================================================================
# Target rules for targets named AITest-dsp

# Build rule for target.
AITest-dsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-dsp
.PHONY : AITest-dsp

# fast build rule for target.
AITest-dsp/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-dsp.dir/build.make plugins/AITest/CMakeFiles/AITest-dsp.dir/build
.PHONY : AITest-dsp/fast

#=============================================================================
# Target rules for targets named AITest-ui

# Build rule for target.
AITest-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-ui
.PHONY : AITest-ui

# fast build rule for target.
AITest-ui/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-ui.dir/build.make plugins/AITest/CMakeFiles/AITest-ui.dir/build
.PHONY : AITest-ui/fast

#=============================================================================
# Target rules for targets named AITest-jack

# Build rule for target.
AITest-jack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-jack
.PHONY : AITest-jack

# fast build rule for target.
AITest-jack/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-jack.dir/build.make plugins/AITest/CMakeFiles/AITest-jack.dir/build
.PHONY : AITest-jack/fast

#=============================================================================
# Target rules for targets named AITest-lv2

# Build rule for target.
AITest-lv2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-lv2
.PHONY : AITest-lv2

# fast build rule for target.
AITest-lv2/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-lv2.dir/build.make plugins/AITest/CMakeFiles/AITest-lv2.dir/build
.PHONY : AITest-lv2/fast

#=============================================================================
# Target rules for targets named AITest-lv2-ui

# Build rule for target.
AITest-lv2-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-lv2-ui
.PHONY : AITest-lv2-ui

# fast build rule for target.
AITest-lv2-ui/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-lv2-ui.dir/build.make plugins/AITest/CMakeFiles/AITest-lv2-ui.dir/build
.PHONY : AITest-lv2-ui/fast

#=============================================================================
# Target rules for targets named lv2_ttl_generator

# Build rule for target.
lv2_ttl_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lv2_ttl_generator
.PHONY : lv2_ttl_generator

# fast build rule for target.
lv2_ttl_generator/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/lv2_ttl_generator.dir/build.make plugins/AITest/CMakeFiles/lv2_ttl_generator.dir/build
.PHONY : lv2_ttl_generator/fast

#=============================================================================
# Target rules for targets named AITest-vst2

# Build rule for target.
AITest-vst2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AITest-vst2
.PHONY : AITest-vst2

# fast build rule for target.
AITest-vst2/fast:
	$(MAKE) $(MAKESILENT) -f plugins/AITest/CMakeFiles/AITest-vst2.dir/build.make plugins/AITest/CMakeFiles/AITest-vst2.dir/build
.PHONY : AITest-vst2/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AITest"
	@echo "... AITest-dsp"
	@echo "... AITest-jack"
	@echo "... AITest-lv2"
	@echo "... AITest-lv2-ui"
	@echo "... AITest-ui"
	@echo "... AITest-vst2"
	@echo "... dgl-opengl"
	@echo "... lv2_ttl_generator"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

